name: "Hello Action"
description: "Greet someone"
author: "raypot.salute@gmail.com"

inputs:
  MY_NAME: 
    description: "Who to greet"
    required: true
    default: "Unknown"
  
runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
